In [1]:
!pip install numpy

### Numpy -- play with array ( numbers )
### Pandas -- dataset
### Matplotlib -- Data visualization
### seaborn -- Data visualization
### Scipy -- Statistical analysis
### Sklearn -- Algorithm

# Numpy: package for Multidimesional array

In [2]:
import numpy as np

In [3]:
n = np.array((1,2,3))
print(n)

[1 2 3]


In [4]:
print(type(n))

<class 'numpy.ndarray'>


In [5]:
List=[[1,2,3],[4,5,6],[7,8,9]]
np.array(List)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(1,36,5) # shift+tab = help box

array([ 1,  6, 11, 16, 21, 26, 31])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones(10, int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [22]:
np.random.rand(3,5)

array([[0.99313972, 0.80059909, 0.03476452, 0.43221425, 0.99675817],
       [0.66668089, 0.77190039, 0.44398948, 0.3875432 , 0.29063072],
       [0.96270397, 0.42516836, 0.00716149, 0.88594621, 0.02264742]])

In [23]:
arr= np.random.randn(2,4)
arr

array([[-1.99554713, -0.51267912,  1.59146794,  0.5367547 ],
       [ 0.04850388, -0.06135405, -1.13526388,  1.34633604]])

In [24]:
np.random.randint(2,100)

66

In [25]:
np.random.randint(20,56,100)

array([48, 26, 47, 26, 24, 51, 42, 37, 21, 38, 51, 30, 44, 48, 40, 54, 52,
       27, 23, 53, 22, 34, 47, 25, 46, 42, 38, 49, 30, 41, 50, 23, 33, 21,
       36, 42, 52, 48, 53, 21, 33, 32, 25, 20, 29, 29, 20, 53, 24, 55, 30,
       21, 50, 51, 29, 43, 30, 27, 28, 37, 51, 23, 20, 21, 51, 20, 21, 42,
       49, 24, 51, 30, 53, 49, 32, 45, 37, 21, 25, 48, 48, 34, 54, 52, 49,
       36, 30, 32, 43, 49, 39, 27, 38, 44, 42, 27, 44, 48, 47, 49])

In [26]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
rand_array=np.random.randint(0,10,50)
rand_array

array([3, 7, 6, 3, 5, 4, 1, 8, 5, 7, 6, 0, 3, 2, 7, 5, 3, 6, 0, 1, 0, 8,
       3, 3, 2, 2, 8, 0, 3, 1, 6, 6, 7, 3, 0, 5, 9, 5, 9, 7, 7, 7, 3, 0,
       1, 0, 0, 3, 2, 3])

In [28]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [29]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [30]:
rand_array.max()

9

In [31]:
rand_array.argmax()

36

In [32]:
rand_array.min()

0

In [33]:
rand_array.argmin()

11

In [34]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
a=np.random.rand(2,3)
a

array([[0.33704666, 0.816751  , 0.46389789],
       [0.67717235, 0.70930631, 0.66568114]])

In [37]:
a.T

array([[0.33704666, 0.67717235],
       [0.816751  , 0.70930631],
       [0.46389789, 0.66568114]])

In [38]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
sample_array[0]

10

In [40]:
sample_array[2:5]

array([12, 13, 14])

In [41]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [42]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [45]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [46]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])